# Generated by Django 6.1.1 on 2026-09-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('da_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('other_allowance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('esi_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pf_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
