# Generated by Django 6.1.1 on 2026-09-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='da_percentage',
            new_name='da_percent',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='hra_percentage',
            new_name='hra_percent',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='other_allowance_percentage',
            new_name='other_allowance_percent',
        ),
    ]
