# Generated by Django 6.1.1 on 2026-09-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_payslip'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('employee', 'month'), name='unique_employee_month_payslip'),
        ),
    ]
